export const  SEARCH_BY_KEYWORDS = 'SEARCH_BY_KEYWORDS'
export const SET_SEARCH_KEYWORDS = 'SET_SEARCH_KEYWORDS'
export const SEARCH_BY_STARS = 'SEARCH_BY_STARS'
export const SET_SEARCH_STARS_COUNT = 'SET_SEARCH_STARS_COUNT'
