export const  REQUEST_REVIEWS = 'REQUEST_REVIEWS';
export const  REVIEWS_FETCHED = 'REVIEWS_FETCHED'
export const  REVIEWS_FETCH_ERROR = 'REVIEWS_FETCH_ERROR'
export const  LOAD_MORE_REVIEWS = 'LOAD_MORE_REVIEWS'
